// Code generated by protoc-gen-go. DO NOT EDIT.
// source: topic.proto

package topic

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	options "github.com/infobloxopen/protoc-gen-gorm/options"
	question "github.com/piex/interview/protorepo/question"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Timestamp from public import google/protobuf/timestamp.proto
type Timestamp = timestamp.Timestamp

// GormFileOptions from public import github.com/infobloxopen/protoc-gen-gorm/options/gorm.proto
type GormFileOptions = options.GormFileOptions

// GormMessageOptions from public import github.com/infobloxopen/protoc-gen-gorm/options/gorm.proto
type GormMessageOptions = options.GormMessageOptions

// ExtraField from public import github.com/infobloxopen/protoc-gen-gorm/options/gorm.proto
type ExtraField = options.ExtraField

// GormFieldOptions from public import github.com/infobloxopen/protoc-gen-gorm/options/gorm.proto
type GormFieldOptions = options.GormFieldOptions
type GormFieldOptions_HasOne = options.GormFieldOptions_HasOne
type GormFieldOptions_BelongsTo = options.GormFieldOptions_BelongsTo
type GormFieldOptions_HasMany = options.GormFieldOptions_HasMany
type GormFieldOptions_ManyToMany = options.GormFieldOptions_ManyToMany

// GormTag from public import github.com/infobloxopen/protoc-gen-gorm/options/gorm.proto
type GormTag = options.GormTag

// HasOneOptions from public import github.com/infobloxopen/protoc-gen-gorm/options/gorm.proto
type HasOneOptions = options.HasOneOptions

// BelongsToOptions from public import github.com/infobloxopen/protoc-gen-gorm/options/gorm.proto
type BelongsToOptions = options.BelongsToOptions

// HasManyOptions from public import github.com/infobloxopen/protoc-gen-gorm/options/gorm.proto
type HasManyOptions = options.HasManyOptions

// ManyToManyOptions from public import github.com/infobloxopen/protoc-gen-gorm/options/gorm.proto
type ManyToManyOptions = options.ManyToManyOptions

// AutoServerOptions from public import github.com/infobloxopen/protoc-gen-gorm/options/gorm.proto
type AutoServerOptions = options.AutoServerOptions

// MethodOptions from public import github.com/infobloxopen/protoc-gen-gorm/options/gorm.proto
type MethodOptions = options.MethodOptions

var E_FileOpts = options.E_FileOpts

var E_Opts = options.E_Opts

var E_Field = options.E_Field

var E_Server = options.E_Server

var E_Method = options.E_Method

// Question from public import github.com/piex/interview/protorepo/question/question.proto
type Question = question.Question

// GetQuestionListRequest from public import github.com/piex/interview/protorepo/question/question.proto
type GetQuestionListRequest = question.GetQuestionListRequest

// QuestionList from public import github.com/piex/interview/protorepo/question/question.proto
type QuestionList = question.QuestionList

// CreateQuestionResponse from public import github.com/piex/interview/protorepo/question/question.proto
type CreateQuestionResponse = question.CreateQuestionResponse

// UpdateQuestionResponse from public import github.com/piex/interview/protorepo/question/question.proto
type UpdateQuestionResponse = question.UpdateQuestionResponse

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_7312ad0e4fa171e8, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Topic struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Slug                 string               `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Topic) Reset()         { *m = Topic{} }
func (m *Topic) String() string { return proto.CompactTextString(m) }
func (*Topic) ProtoMessage()    {}
func (*Topic) Descriptor() ([]byte, []int) {
	return fileDescriptor_7312ad0e4fa171e8, []int{1}
}

func (m *Topic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Topic.Unmarshal(m, b)
}
func (m *Topic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Topic.Marshal(b, m, deterministic)
}
func (m *Topic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Topic.Merge(m, src)
}
func (m *Topic) XXX_Size() int {
	return xxx_messageInfo_Topic.Size(m)
}
func (m *Topic) XXX_DiscardUnknown() {
	xxx_messageInfo_Topic.DiscardUnknown(m)
}

var xxx_messageInfo_Topic proto.InternalMessageInfo

func (m *Topic) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Topic) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Topic) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Topic) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

type QuTopic struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	QuId                 int64                `protobuf:"varint,4,opt,name=quId,proto3" json:"quId,omitempty"`
	TopicId              int64                `protobuf:"varint,5,opt,name=topicId,proto3" json:"topicId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *QuTopic) Reset()         { *m = QuTopic{} }
func (m *QuTopic) String() string { return proto.CompactTextString(m) }
func (*QuTopic) ProtoMessage()    {}
func (*QuTopic) Descriptor() ([]byte, []int) {
	return fileDescriptor_7312ad0e4fa171e8, []int{2}
}

func (m *QuTopic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuTopic.Unmarshal(m, b)
}
func (m *QuTopic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuTopic.Marshal(b, m, deterministic)
}
func (m *QuTopic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuTopic.Merge(m, src)
}
func (m *QuTopic) XXX_Size() int {
	return xxx_messageInfo_QuTopic.Size(m)
}
func (m *QuTopic) XXX_DiscardUnknown() {
	xxx_messageInfo_QuTopic.DiscardUnknown(m)
}

var xxx_messageInfo_QuTopic proto.InternalMessageInfo

func (m *QuTopic) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *QuTopic) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *QuTopic) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *QuTopic) GetQuId() int64 {
	if m != nil {
		return m.QuId
	}
	return 0
}

func (m *QuTopic) GetTopicId() int64 {
	if m != nil {
		return m.TopicId
	}
	return 0
}

type TopicList struct {
	Total                int64    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Topics               []*Topic `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopicList) Reset()         { *m = TopicList{} }
func (m *TopicList) String() string { return proto.CompactTextString(m) }
func (*TopicList) ProtoMessage()    {}
func (*TopicList) Descriptor() ([]byte, []int) {
	return fileDescriptor_7312ad0e4fa171e8, []int{3}
}

func (m *TopicList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicList.Unmarshal(m, b)
}
func (m *TopicList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicList.Marshal(b, m, deterministic)
}
func (m *TopicList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicList.Merge(m, src)
}
func (m *TopicList) XXX_Size() int {
	return xxx_messageInfo_TopicList.Size(m)
}
func (m *TopicList) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicList.DiscardUnknown(m)
}

var xxx_messageInfo_TopicList proto.InternalMessageInfo

func (m *TopicList) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *TopicList) GetTopics() []*Topic {
	if m != nil {
		return m.Topics
	}
	return nil
}

type CreateTopicResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTopicResponse) Reset()         { *m = CreateTopicResponse{} }
func (m *CreateTopicResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTopicResponse) ProtoMessage()    {}
func (*CreateTopicResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7312ad0e4fa171e8, []int{4}
}

func (m *CreateTopicResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTopicResponse.Unmarshal(m, b)
}
func (m *CreateTopicResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTopicResponse.Marshal(b, m, deterministic)
}
func (m *CreateTopicResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTopicResponse.Merge(m, src)
}
func (m *CreateTopicResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTopicResponse.Size(m)
}
func (m *CreateTopicResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTopicResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTopicResponse proto.InternalMessageInfo

func (m *CreateTopicResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetTopicRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTopicRequest) Reset()         { *m = GetTopicRequest{} }
func (m *GetTopicRequest) String() string { return proto.CompactTextString(m) }
func (*GetTopicRequest) ProtoMessage()    {}
func (*GetTopicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7312ad0e4fa171e8, []int{5}
}

func (m *GetTopicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTopicRequest.Unmarshal(m, b)
}
func (m *GetTopicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTopicRequest.Marshal(b, m, deterministic)
}
func (m *GetTopicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTopicRequest.Merge(m, src)
}
func (m *GetTopicRequest) XXX_Size() int {
	return xxx_messageInfo_GetTopicRequest.Size(m)
}
func (m *GetTopicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTopicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTopicRequest proto.InternalMessageInfo

func (m *GetTopicRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetTopicsByQuRequest struct {
	QuId                 int64    `protobuf:"varint,1,opt,name=qu_id,json=quId,proto3" json:"qu_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTopicsByQuRequest) Reset()         { *m = GetTopicsByQuRequest{} }
func (m *GetTopicsByQuRequest) String() string { return proto.CompactTextString(m) }
func (*GetTopicsByQuRequest) ProtoMessage()    {}
func (*GetTopicsByQuRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7312ad0e4fa171e8, []int{6}
}

func (m *GetTopicsByQuRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTopicsByQuRequest.Unmarshal(m, b)
}
func (m *GetTopicsByQuRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTopicsByQuRequest.Marshal(b, m, deterministic)
}
func (m *GetTopicsByQuRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTopicsByQuRequest.Merge(m, src)
}
func (m *GetTopicsByQuRequest) XXX_Size() int {
	return xxx_messageInfo_GetTopicsByQuRequest.Size(m)
}
func (m *GetTopicsByQuRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTopicsByQuRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTopicsByQuRequest proto.InternalMessageInfo

func (m *GetTopicsByQuRequest) GetQuId() int64 {
	if m != nil {
		return m.QuId
	}
	return 0
}

type GetQusByTopicRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	TopicId              int64    `protobuf:"varint,3,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetQusByTopicRequest) Reset()         { *m = GetQusByTopicRequest{} }
func (m *GetQusByTopicRequest) String() string { return proto.CompactTextString(m) }
func (*GetQusByTopicRequest) ProtoMessage()    {}
func (*GetQusByTopicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7312ad0e4fa171e8, []int{7}
}

func (m *GetQusByTopicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQusByTopicRequest.Unmarshal(m, b)
}
func (m *GetQusByTopicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQusByTopicRequest.Marshal(b, m, deterministic)
}
func (m *GetQusByTopicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQusByTopicRequest.Merge(m, src)
}
func (m *GetQusByTopicRequest) XXX_Size() int {
	return xxx_messageInfo_GetQusByTopicRequest.Size(m)
}
func (m *GetQusByTopicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQusByTopicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetQusByTopicRequest proto.InternalMessageInfo

func (m *GetQusByTopicRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetQusByTopicRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *GetQusByTopicRequest) GetTopicId() int64 {
	if m != nil {
		return m.TopicId
	}
	return 0
}

type GetQusByTopicResponse struct {
	Qus                  []int64  `protobuf:"varint,1,rep,packed,name=qus,proto3" json:"qus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetQusByTopicResponse) Reset()         { *m = GetQusByTopicResponse{} }
func (m *GetQusByTopicResponse) String() string { return proto.CompactTextString(m) }
func (*GetQusByTopicResponse) ProtoMessage()    {}
func (*GetQusByTopicResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7312ad0e4fa171e8, []int{8}
}

func (m *GetQusByTopicResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQusByTopicResponse.Unmarshal(m, b)
}
func (m *GetQusByTopicResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQusByTopicResponse.Marshal(b, m, deterministic)
}
func (m *GetQusByTopicResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQusByTopicResponse.Merge(m, src)
}
func (m *GetQusByTopicResponse) XXX_Size() int {
	return xxx_messageInfo_GetQusByTopicResponse.Size(m)
}
func (m *GetQusByTopicResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQusByTopicResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetQusByTopicResponse proto.InternalMessageInfo

func (m *GetQusByTopicResponse) GetQus() []int64 {
	if m != nil {
		return m.Qus
	}
	return nil
}

type AddTopicsToQuestionRequest struct {
	QuId                 int64    `protobuf:"varint,1,opt,name=qu_id,json=quId,proto3" json:"qu_id,omitempty"`
	TopicId              []int64  `protobuf:"varint,2,rep,packed,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTopicsToQuestionRequest) Reset()         { *m = AddTopicsToQuestionRequest{} }
func (m *AddTopicsToQuestionRequest) String() string { return proto.CompactTextString(m) }
func (*AddTopicsToQuestionRequest) ProtoMessage()    {}
func (*AddTopicsToQuestionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7312ad0e4fa171e8, []int{9}
}

func (m *AddTopicsToQuestionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTopicsToQuestionRequest.Unmarshal(m, b)
}
func (m *AddTopicsToQuestionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTopicsToQuestionRequest.Marshal(b, m, deterministic)
}
func (m *AddTopicsToQuestionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTopicsToQuestionRequest.Merge(m, src)
}
func (m *AddTopicsToQuestionRequest) XXX_Size() int {
	return xxx_messageInfo_AddTopicsToQuestionRequest.Size(m)
}
func (m *AddTopicsToQuestionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTopicsToQuestionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddTopicsToQuestionRequest proto.InternalMessageInfo

func (m *AddTopicsToQuestionRequest) GetQuId() int64 {
	if m != nil {
		return m.QuId
	}
	return 0
}

func (m *AddTopicsToQuestionRequest) GetTopicId() []int64 {
	if m != nil {
		return m.TopicId
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "interview.topic.Empty")
	proto.RegisterType((*Topic)(nil), "interview.topic.Topic")
	proto.RegisterType((*QuTopic)(nil), "interview.topic.QuTopic")
	proto.RegisterType((*TopicList)(nil), "interview.topic.TopicList")
	proto.RegisterType((*CreateTopicResponse)(nil), "interview.topic.CreateTopicResponse")
	proto.RegisterType((*GetTopicRequest)(nil), "interview.topic.GetTopicRequest")
	proto.RegisterType((*GetTopicsByQuRequest)(nil), "interview.topic.GetTopicsByQuRequest")
	proto.RegisterType((*GetQusByTopicRequest)(nil), "interview.topic.GetQusByTopicRequest")
	proto.RegisterType((*GetQusByTopicResponse)(nil), "interview.topic.GetQusByTopicResponse")
	proto.RegisterType((*AddTopicsToQuestionRequest)(nil), "interview.topic.AddTopicsToQuestionRequest")
}

func init() { proto.RegisterFile("topic.proto", fileDescriptor_7312ad0e4fa171e8) }

var fileDescriptor_7312ad0e4fa171e8 = []byte{
	// 637 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x54, 0x4f, 0x6f, 0xda, 0x4e,
	0x10, 0xc5, 0x36, 0x0e, 0x30, 0x24, 0xbf, 0x44, 0x9b, 0xfc, 0x2a, 0x58, 0x55, 0x2a, 0x5d, 0x35,
	0x12, 0x55, 0x14, 0x5b, 0x4a, 0x6f, 0xe9, 0xa5, 0xa1, 0x7f, 0x23, 0xa5, 0x52, 0x70, 0xb9, 0x34,
	0xaa, 0x14, 0x01, 0xde, 0xb8, 0x96, 0x80, 0x35, 0xec, 0x6e, 0x9b, 0xf4, 0xd6, 0x8f, 0x05, 0x9f,
	0xa4, 0xdf, 0xa5, 0x97, 0xca, 0x63, 0x9b, 0x00, 0x86, 0x56, 0x3d, 0xf6, 0xb6, 0x8c, 0xdf, 0x7b,
	0x3b, 0xef, 0xcd, 0xb0, 0x50, 0x55, 0x22, 0x0a, 0xfb, 0x4e, 0x34, 0x11, 0x4a, 0x90, 0xdd, 0x70,
	0xa4, 0xf8, 0xe4, 0x4b, 0xc8, 0xbf, 0x3a, 0x58, 0xa6, 0x8f, 0x02, 0x21, 0x82, 0x01, 0x77, 0xf1,
	0x73, 0x4f, 0xdf, 0xb8, 0x2a, 0x1c, 0x72, 0xa9, 0xba, 0xc3, 0x28, 0x61, 0xd0, 0xd3, 0x20, 0x54,
	0x9f, 0x75, 0xcf, 0xe9, 0x8b, 0xa1, 0x1b, 0x8e, 0x6e, 0x44, 0x6f, 0x20, 0x6e, 0x45, 0xc4, 0x47,
	0x09, 0xa3, 0x7f, 0x1c, 0xf0, 0xd1, 0x71, 0x20, 0x26, 0x43, 0x57, 0x44, 0x2a, 0x14, 0x23, 0xe9,
	0xc6, 0x3f, 0x52, 0xee, 0xf3, 0x05, 0x6e, 0x14, 0xf2, 0x5b, 0x77, 0x7e, 0x7b, 0xc2, 0x9e, 0xf0,
	0x48, 0xb8, 0x63, 0xcd, 0x65, 0xcc, 0x9c, 0x1f, 0x12, 0x32, 0x2b, 0x81, 0xfd, 0x7a, 0x18, 0xa9,
	0x3b, 0xf6, 0xc3, 0x00, 0xbb, 0x13, 0x37, 0x4b, 0x28, 0x98, 0xa1, 0x5f, 0x33, 0x1a, 0x46, 0xd3,
	0x6a, 0xc1, 0x6c, 0x5a, 0xdf, 0x82, 0x62, 0xd3, 0x78, 0x67, 0x78, 0x66, 0xe8, 0x93, 0x16, 0x54,
	0xfa, 0x13, 0xde, 0x55, 0xdc, 0x3f, 0x53, 0x35, 0xb3, 0x61, 0x34, 0xab, 0x27, 0xd4, 0x49, 0xcc,
	0x39, 0x99, 0x39, 0xa7, 0x93, 0x99, 0x6b, 0x95, 0x67, 0xd3, 0x7a, 0x11, 0xcc, 0x17, 0x86, 0x77,
	0x4f, 0x8b, 0x35, 0x74, 0xe4, 0xa7, 0x1a, 0xd6, 0xdf, 0x68, 0xcc, 0x69, 0xe4, 0x21, 0x14, 0xe5,
	0x40, 0x07, 0xb5, 0x62, 0xc3, 0x68, 0x56, 0x16, 0x20, 0x58, 0x3d, 0xdd, 0x99, 0x4d, 0xeb, 0x95,
	0xb2, 0x41, 0x6d, 0x4c, 0x9f, 0x7d, 0x37, 0xa1, 0xd4, 0xd6, 0xff, 0x94, 0xb9, 0xb1, 0x3e, 0xf7,
	0xd1, 0x9c, 0xb5, 0x68, 0x2e, 0xae, 0x12, 0x06, 0x25, 0xb4, 0x75, 0xee, 0xd7, 0xec, 0x15, 0x40,
	0xf6, 0xe1, 0x74, 0x6f, 0x36, 0xad, 0x6f, 0x97, 0x0d, 0x5a, 0x1e, 0xeb, 0xeb, 0x24, 0x83, 0x36,
	0x54, 0x30, 0x80, 0x8b, 0x50, 0x2a, 0x72, 0x00, 0xb6, 0x12, 0xaa, 0x3b, 0x48, 0x72, 0xf0, 0x92,
	0x1f, 0xc4, 0x81, 0x2d, 0xc4, 0xca, 0x9a, 0xd9, 0xb0, 0x9a, 0xd5, 0x93, 0x07, 0xce, 0xca, 0x1a,
	0x3b, 0xa8, 0xe0, 0xa5, 0x28, 0x76, 0x08, 0xfb, 0x2f, 0xd1, 0x77, 0x52, 0xe6, 0x32, 0x12, 0x23,
	0xc9, 0xc9, 0x7f, 0xf7, 0x09, 0xc7, 0xa9, 0xb2, 0xc7, 0xb0, 0xfb, 0x96, 0xab, 0x14, 0x83, 0xdb,
	0x97, 0x83, 0x1c, 0xc1, 0x41, 0x06, 0x91, 0xad, 0xbb, 0xb6, 0xce, 0x70, 0xfb, 0x60, 0x8f, 0xf5,
	0xf5, 0x1c, 0x8a, 0xfe, 0xd9, 0x47, 0x04, 0xb7, 0xb5, 0x6c, 0xdd, 0x2d, 0x89, 0x12, 0x28, 0x46,
	0xdd, 0x80, 0x23, 0xd6, 0xf6, 0xf0, 0x1c, 0xd7, 0x64, 0xf8, 0x8d, 0xe3, 0x30, 0x6d, 0x0f, 0xcf,
	0xa4, 0x0e, 0x65, 0x34, 0x10, 0xeb, 0x5a, 0xa8, 0x9b, 0xc5, 0xc6, 0x9e, 0xc2, 0xff, 0x2b, 0xd2,
	0xa9, 0xa7, 0x3d, 0xb0, 0xc6, 0x5a, 0xd6, 0x8c, 0x86, 0xd5, 0xb4, 0xbc, 0xf8, 0xc8, 0x2e, 0x80,
	0x9e, 0xf9, 0x7e, 0xd2, 0x72, 0x47, 0xb4, 0xd3, 0x3f, 0xd5, 0xef, 0x1a, 0x5f, 0xba, 0xd8, 0x44,
	0xa5, 0xec, 0xe2, 0x93, 0x9f, 0x16, 0x6c, 0xa3, 0xd6, 0x87, 0x38, 0xef, 0x3e, 0x27, 0xef, 0xa1,
	0xba, 0x90, 0x2d, 0xd9, 0x30, 0x0a, 0xfa, 0x24, 0x57, 0x5f, 0x33, 0x11, 0x56, 0x20, 0xaf, 0x60,
	0x3b, 0x0b, 0x18, 0x17, 0x20, 0xaf, 0x87, 0x8f, 0x00, 0xa5, 0xeb, 0xef, 0x89, 0x39, 0xac, 0x40,
	0xde, 0x40, 0x39, 0x53, 0x21, 0x8d, 0x1c, 0x72, 0x65, 0xc8, 0x74, 0x43, 0xcf, 0xac, 0x40, 0x3a,
	0xb0, 0xb3, 0x34, 0x6e, 0x72, 0xb8, 0x51, 0x6c, 0x71, 0x1d, 0xfe, 0xd0, 0xdd, 0x15, 0xaa, 0xde,
	0x0f, 0x6f, 0xbd, 0x6a, 0x6e, 0x6f, 0xe8, 0xa2, 0x93, 0xf9, 0xe3, 0x98, 0x0d, 0x34, 0xd5, 0xfe,
	0x04, 0xfb, 0x6b, 0xa6, 0x4d, 0x8e, 0x72, 0x37, 0x6c, 0xde, 0x09, 0xba, 0x21, 0x73, 0x56, 0x68,
	0x95, 0xae, 0x92, 0x87, 0xea, 0xb2, 0x70, 0x69, 0x5c, 0x9a, 0xbd, 0x2d, 0x7c, 0x27, 0x9e, 0xfd,
	0x0a, 0x00, 0x00, 0xff, 0xff, 0x9f, 0xe8, 0x6f, 0x79, 0x53, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TopicServiceClient is the client API for TopicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TopicServiceClient interface {
	// 创建
	CreateTopic(ctx context.Context, in *Topic, opts ...grpc.CallOption) (*CreateTopicResponse, error)
	// 查找全部 topic
	GetTopicList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TopicList, error)
	GetTopic(ctx context.Context, in *GetTopicRequest, opts ...grpc.CallOption) (*Topic, error)
	// 查询 qu 的 topic
	GetTopicsByQu(ctx context.Context, in *GetTopicsByQuRequest, opts ...grpc.CallOption) (*TopicList, error)
	// 查找有指定 topic 的 qus
	GetQusByTopic(ctx context.Context, in *GetQusByTopicRequest, opts ...grpc.CallOption) (*question.QuestionList, error)
	// qu 添加 topic
	AddTopicsToQuestion(ctx context.Context, in *AddTopicsToQuestionRequest, opts ...grpc.CallOption) (*Empty, error)
}

type topicServiceClient struct {
	cc *grpc.ClientConn
}

func NewTopicServiceClient(cc *grpc.ClientConn) TopicServiceClient {
	return &topicServiceClient{cc}
}

func (c *topicServiceClient) CreateTopic(ctx context.Context, in *Topic, opts ...grpc.CallOption) (*CreateTopicResponse, error) {
	out := new(CreateTopicResponse)
	err := c.cc.Invoke(ctx, "/interview.topic.TopicService/CreateTopic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topicServiceClient) GetTopicList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TopicList, error) {
	out := new(TopicList)
	err := c.cc.Invoke(ctx, "/interview.topic.TopicService/GetTopicList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topicServiceClient) GetTopic(ctx context.Context, in *GetTopicRequest, opts ...grpc.CallOption) (*Topic, error) {
	out := new(Topic)
	err := c.cc.Invoke(ctx, "/interview.topic.TopicService/GetTopic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topicServiceClient) GetTopicsByQu(ctx context.Context, in *GetTopicsByQuRequest, opts ...grpc.CallOption) (*TopicList, error) {
	out := new(TopicList)
	err := c.cc.Invoke(ctx, "/interview.topic.TopicService/GetTopicsByQu", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topicServiceClient) GetQusByTopic(ctx context.Context, in *GetQusByTopicRequest, opts ...grpc.CallOption) (*question.QuestionList, error) {
	out := new(question.QuestionList)
	err := c.cc.Invoke(ctx, "/interview.topic.TopicService/GetQusByTopic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topicServiceClient) AddTopicsToQuestion(ctx context.Context, in *AddTopicsToQuestionRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/interview.topic.TopicService/AddTopicsToQuestion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TopicServiceServer is the server API for TopicService service.
type TopicServiceServer interface {
	// 创建
	CreateTopic(context.Context, *Topic) (*CreateTopicResponse, error)
	// 查找全部 topic
	GetTopicList(context.Context, *Empty) (*TopicList, error)
	GetTopic(context.Context, *GetTopicRequest) (*Topic, error)
	// 查询 qu 的 topic
	GetTopicsByQu(context.Context, *GetTopicsByQuRequest) (*TopicList, error)
	// 查找有指定 topic 的 qus
	GetQusByTopic(context.Context, *GetQusByTopicRequest) (*question.QuestionList, error)
	// qu 添加 topic
	AddTopicsToQuestion(context.Context, *AddTopicsToQuestionRequest) (*Empty, error)
}

func RegisterTopicServiceServer(s *grpc.Server, srv TopicServiceServer) {
	s.RegisterService(&_TopicService_serviceDesc, srv)
}

func _TopicService_CreateTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Topic)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopicServiceServer).CreateTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interview.topic.TopicService/CreateTopic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopicServiceServer).CreateTopic(ctx, req.(*Topic))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopicService_GetTopicList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopicServiceServer).GetTopicList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interview.topic.TopicService/GetTopicList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopicServiceServer).GetTopicList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopicService_GetTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopicServiceServer).GetTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interview.topic.TopicService/GetTopic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopicServiceServer).GetTopic(ctx, req.(*GetTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopicService_GetTopicsByQu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopicsByQuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopicServiceServer).GetTopicsByQu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interview.topic.TopicService/GetTopicsByQu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopicServiceServer).GetTopicsByQu(ctx, req.(*GetTopicsByQuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopicService_GetQusByTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQusByTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopicServiceServer).GetQusByTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interview.topic.TopicService/GetQusByTopic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopicServiceServer).GetQusByTopic(ctx, req.(*GetQusByTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopicService_AddTopicsToQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTopicsToQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopicServiceServer).AddTopicsToQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interview.topic.TopicService/AddTopicsToQuestion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopicServiceServer).AddTopicsToQuestion(ctx, req.(*AddTopicsToQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TopicService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "interview.topic.TopicService",
	HandlerType: (*TopicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTopic",
			Handler:    _TopicService_CreateTopic_Handler,
		},
		{
			MethodName: "GetTopicList",
			Handler:    _TopicService_GetTopicList_Handler,
		},
		{
			MethodName: "GetTopic",
			Handler:    _TopicService_GetTopic_Handler,
		},
		{
			MethodName: "GetTopicsByQu",
			Handler:    _TopicService_GetTopicsByQu_Handler,
		},
		{
			MethodName: "GetQusByTopic",
			Handler:    _TopicService_GetQusByTopic_Handler,
		},
		{
			MethodName: "AddTopicsToQuestion",
			Handler:    _TopicService_AddTopicsToQuestion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "topic.proto",
}
