// Code generated by protoc-gen-go. DO NOT EDIT.
// source: question.proto

package question

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	options "github.com/infobloxopen/protoc-gen-gorm/options"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Timestamp from public import google/protobuf/timestamp.proto
type Timestamp = timestamp.Timestamp

// GormFileOptions from public import github.com/infobloxopen/protoc-gen-gorm/options/gorm.proto
type GormFileOptions = options.GormFileOptions

// GormMessageOptions from public import github.com/infobloxopen/protoc-gen-gorm/options/gorm.proto
type GormMessageOptions = options.GormMessageOptions

// ExtraField from public import github.com/infobloxopen/protoc-gen-gorm/options/gorm.proto
type ExtraField = options.ExtraField

// GormFieldOptions from public import github.com/infobloxopen/protoc-gen-gorm/options/gorm.proto
type GormFieldOptions = options.GormFieldOptions
type GormFieldOptions_HasOne = options.GormFieldOptions_HasOne
type GormFieldOptions_BelongsTo = options.GormFieldOptions_BelongsTo
type GormFieldOptions_HasMany = options.GormFieldOptions_HasMany
type GormFieldOptions_ManyToMany = options.GormFieldOptions_ManyToMany

// GormTag from public import github.com/infobloxopen/protoc-gen-gorm/options/gorm.proto
type GormTag = options.GormTag

// HasOneOptions from public import github.com/infobloxopen/protoc-gen-gorm/options/gorm.proto
type HasOneOptions = options.HasOneOptions

// BelongsToOptions from public import github.com/infobloxopen/protoc-gen-gorm/options/gorm.proto
type BelongsToOptions = options.BelongsToOptions

// HasManyOptions from public import github.com/infobloxopen/protoc-gen-gorm/options/gorm.proto
type HasManyOptions = options.HasManyOptions

// ManyToManyOptions from public import github.com/infobloxopen/protoc-gen-gorm/options/gorm.proto
type ManyToManyOptions = options.ManyToManyOptions

// AutoServerOptions from public import github.com/infobloxopen/protoc-gen-gorm/options/gorm.proto
type AutoServerOptions = options.AutoServerOptions

// MethodOptions from public import github.com/infobloxopen/protoc-gen-gorm/options/gorm.proto
type MethodOptions = options.MethodOptions

var E_FileOpts = options.E_FileOpts

var E_Opts = options.E_Opts

var E_Field = options.E_Field

var E_Server = options.E_Server

var E_Method = options.E_Method

type Question struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Title                string               `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Summary              string               `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	Content              string               `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Difficulty           int32                `protobuf:"varint,7,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Question) Reset()         { *m = Question{} }
func (m *Question) String() string { return proto.CompactTextString(m) }
func (*Question) ProtoMessage()    {}
func (*Question) Descriptor() ([]byte, []int) {
	return fileDescriptor_64d310e1b23c85d7, []int{0}
}

func (m *Question) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Question.Unmarshal(m, b)
}
func (m *Question) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Question.Marshal(b, m, deterministic)
}
func (m *Question) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Question.Merge(m, src)
}
func (m *Question) XXX_Size() int {
	return xxx_messageInfo_Question.Size(m)
}
func (m *Question) XXX_DiscardUnknown() {
	xxx_messageInfo_Question.DiscardUnknown(m)
}

var xxx_messageInfo_Question proto.InternalMessageInfo

func (m *Question) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Question) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Question) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Question) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Question) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *Question) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Question) GetDifficulty() int32 {
	if m != nil {
		return m.Difficulty
	}
	return 0
}

type GetQuestionListRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Keyword              string   `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetQuestionListRequest) Reset()         { *m = GetQuestionListRequest{} }
func (m *GetQuestionListRequest) String() string { return proto.CompactTextString(m) }
func (*GetQuestionListRequest) ProtoMessage()    {}
func (*GetQuestionListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_64d310e1b23c85d7, []int{1}
}

func (m *GetQuestionListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQuestionListRequest.Unmarshal(m, b)
}
func (m *GetQuestionListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQuestionListRequest.Marshal(b, m, deterministic)
}
func (m *GetQuestionListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQuestionListRequest.Merge(m, src)
}
func (m *GetQuestionListRequest) XXX_Size() int {
	return xxx_messageInfo_GetQuestionListRequest.Size(m)
}
func (m *GetQuestionListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQuestionListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetQuestionListRequest proto.InternalMessageInfo

func (m *GetQuestionListRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetQuestionListRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *GetQuestionListRequest) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

type QuestionList struct {
	Total                int64       `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Questions            []*Question `protobuf:"bytes,2,rep,name=questions,proto3" json:"questions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *QuestionList) Reset()         { *m = QuestionList{} }
func (m *QuestionList) String() string { return proto.CompactTextString(m) }
func (*QuestionList) ProtoMessage()    {}
func (*QuestionList) Descriptor() ([]byte, []int) {
	return fileDescriptor_64d310e1b23c85d7, []int{2}
}

func (m *QuestionList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuestionList.Unmarshal(m, b)
}
func (m *QuestionList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuestionList.Marshal(b, m, deterministic)
}
func (m *QuestionList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuestionList.Merge(m, src)
}
func (m *QuestionList) XXX_Size() int {
	return xxx_messageInfo_QuestionList.Size(m)
}
func (m *QuestionList) XXX_DiscardUnknown() {
	xxx_messageInfo_QuestionList.DiscardUnknown(m)
}

var xxx_messageInfo_QuestionList proto.InternalMessageInfo

func (m *QuestionList) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *QuestionList) GetQuestions() []*Question {
	if m != nil {
		return m.Questions
	}
	return nil
}

type CreateQuestionResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateQuestionResponse) Reset()         { *m = CreateQuestionResponse{} }
func (m *CreateQuestionResponse) String() string { return proto.CompactTextString(m) }
func (*CreateQuestionResponse) ProtoMessage()    {}
func (*CreateQuestionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_64d310e1b23c85d7, []int{3}
}

func (m *CreateQuestionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateQuestionResponse.Unmarshal(m, b)
}
func (m *CreateQuestionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateQuestionResponse.Marshal(b, m, deterministic)
}
func (m *CreateQuestionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateQuestionResponse.Merge(m, src)
}
func (m *CreateQuestionResponse) XXX_Size() int {
	return xxx_messageInfo_CreateQuestionResponse.Size(m)
}
func (m *CreateQuestionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateQuestionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateQuestionResponse proto.InternalMessageInfo

func (m *CreateQuestionResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UpdateQuestionResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateQuestionResponse) Reset()         { *m = UpdateQuestionResponse{} }
func (m *UpdateQuestionResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateQuestionResponse) ProtoMessage()    {}
func (*UpdateQuestionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_64d310e1b23c85d7, []int{4}
}

func (m *UpdateQuestionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateQuestionResponse.Unmarshal(m, b)
}
func (m *UpdateQuestionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateQuestionResponse.Marshal(b, m, deterministic)
}
func (m *UpdateQuestionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateQuestionResponse.Merge(m, src)
}
func (m *UpdateQuestionResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateQuestionResponse.Size(m)
}
func (m *UpdateQuestionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateQuestionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateQuestionResponse proto.InternalMessageInfo

func (m *UpdateQuestionResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*Question)(nil), "interview.question.Question")
	proto.RegisterType((*GetQuestionListRequest)(nil), "interview.question.GetQuestionListRequest")
	proto.RegisterType((*QuestionList)(nil), "interview.question.QuestionList")
	proto.RegisterType((*CreateQuestionResponse)(nil), "interview.question.CreateQuestionResponse")
	proto.RegisterType((*UpdateQuestionResponse)(nil), "interview.question.UpdateQuestionResponse")
}

func init() { proto.RegisterFile("question.proto", fileDescriptor_64d310e1b23c85d7) }

var fileDescriptor_64d310e1b23c85d7 = []byte{
	// 541 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x51, 0x8f, 0xd2, 0x4c,
	0x14, 0x65, 0x0a, 0x85, 0x72, 0x21, 0xec, 0xf7, 0x4d, 0x0c, 0x29, 0x8d, 0xd1, 0xa6, 0x0f, 0x6e,
	0xa3, 0xd9, 0x62, 0xf0, 0x8d, 0xa7, 0x15, 0x4d, 0xf4, 0xc1, 0x87, 0xdd, 0xaa, 0x2f, 0x1b, 0x1f,
	0x2c, 0xed, 0x50, 0x27, 0xb6, 0x9d, 0xda, 0x99, 0xee, 0x8a, 0xaf, 0xfe, 0x2a, 0xf8, 0x27, 0xfe,
	0x1b, 0xd3, 0x29, 0x03, 0xec, 0x2e, 0xc1, 0xe8, 0xdb, 0xdc, 0x39, 0xe7, 0x9e, 0x39, 0xbd, 0xf7,
	0x14, 0x06, 0xdf, 0x4a, 0xc2, 0x05, 0x65, 0x99, 0x97, 0x17, 0x4c, 0x30, 0x8c, 0x69, 0x26, 0x48,
	0x71, 0x4d, 0xc9, 0x8d, 0xa7, 0x10, 0xeb, 0x71, 0xcc, 0x58, 0x9c, 0x90, 0xb1, 0x64, 0xcc, 0xcb,
	0xc5, 0x58, 0xd0, 0x94, 0x70, 0x11, 0xa4, 0x79, 0xdd, 0x64, 0x4d, 0x63, 0x2a, 0xbe, 0x94, 0x73,
	0x2f, 0x64, 0xe9, 0x98, 0x66, 0x0b, 0x36, 0x4f, 0xd8, 0x77, 0x96, 0x93, 0xac, 0xee, 0x08, 0xcf,
	0x62, 0x92, 0x9d, 0xc5, 0xac, 0x48, 0xc7, 0x2c, 0xaf, 0x04, 0xf9, 0xb8, 0x2a, 0xea, 0x5e, 0xe7,
	0x97, 0x06, 0xc6, 0xe5, 0xe6, 0x25, 0x6c, 0x81, 0x46, 0x23, 0x13, 0xd9, 0xc8, 0x6d, 0xce, 0x60,
	0xbd, 0x1a, 0xb5, 0xa1, 0xe5, 0xa2, 0xb7, 0xc8, 0xd7, 0x68, 0x84, 0x67, 0xd0, 0x0d, 0x0b, 0x12,
	0x08, 0x12, 0xbd, 0x14, 0xa6, 0x66, 0x23, 0xb7, 0x37, 0xb1, 0xbc, 0xda, 0x99, 0xa7, 0x9c, 0x79,
	0x1f, 0x94, 0xb3, 0x99, 0xb1, 0x5e, 0x8d, 0x5a, 0xa0, 0x9d, 0x23, 0x7f, 0xd7, 0x56, 0x69, 0x94,
	0x79, 0xb4, 0xd1, 0x68, 0xfe, 0x8d, 0xc6, 0xb6, 0x0d, 0x3f, 0x02, 0x5d, 0x50, 0x91, 0x10, 0xb3,
	0x65, 0x23, 0xb7, 0xbb, 0xc7, 0xa9, 0xaf, 0xb1, 0x03, 0x1d, 0x5e, 0xa6, 0x69, 0x50, 0x2c, 0x4d,
	0xfd, 0x0e, 0x43, 0x01, 0xf8, 0x09, 0x74, 0x42, 0x96, 0x09, 0x92, 0x09, 0xb3, 0x2d, 0x39, 0xfd,
	0xf5, 0x6a, 0x64, 0x40, 0x7b, 0xaa, 0x9d, 0x9e, 0x56, 0xbc, 0x0d, 0x88, 0x9f, 0x01, 0x44, 0x74,
	0xb1, 0xa0, 0x61, 0x99, 0x88, 0xa5, 0xd9, 0xb1, 0x91, 0xab, 0xcf, 0x7a, 0xeb, 0xd5, 0xa8, 0x03,
	0xfa, 0x14, 0x3d, 0x3f, 0x47, 0xfe, 0x1e, 0x3c, 0xfd, 0x6f, 0xbd, 0x1a, 0xf5, 0x0d, 0x64, 0x19,
	0x6a, 0x71, 0xce, 0x15, 0x0c, 0xdf, 0x10, 0xa1, 0xa6, 0xfb, 0x8e, 0x72, 0xe1, 0x13, 0x09, 0x62,
	0x0c, 0xad, 0x3c, 0x88, 0x89, 0x1c, 0xb5, 0xee, 0xcb, 0x73, 0x75, 0xc7, 0xe9, 0x0f, 0x22, 0x67,
	0xab, 0xfb, 0xf2, 0x8c, 0x4d, 0xe8, 0x7c, 0x25, 0xcb, 0x1b, 0x56, 0x44, 0x72, 0x5c, 0x5d, 0x5f,
	0x95, 0xce, 0x67, 0xe8, 0xef, 0x0b, 0xe3, 0x07, 0xa0, 0x0b, 0x26, 0x82, 0xa4, 0xde, 0x9e, 0x5f,
	0x17, 0x78, 0x0a, 0x5d, 0xe5, 0x86, 0x9b, 0x9a, 0xdd, 0x74, 0x7b, 0x93, 0x87, 0xde, 0xfd, 0x88,
	0x79, 0x4a, 0xca, 0xdf, 0xd1, 0x1d, 0x17, 0x86, 0xaf, 0xe4, 0xe6, 0xb6, 0x20, 0xe1, 0x39, 0xcb,
	0x38, 0xc1, 0x83, 0x5d, 0x4c, 0xaa, 0x68, 0x38, 0x13, 0x18, 0x7e, 0x94, 0xfb, 0xb9, 0xc7, 0x34,
	0xab, 0x65, 0x84, 0x21, 0xe1, 0x5c, 0xd2, 0x0d, 0x5f, 0x95, 0x93, 0x9f, 0x4d, 0x38, 0x51, 0xf4,
	0xf7, 0x95, 0x9d, 0x6b, 0x82, 0x3f, 0xc1, 0xe0, 0xf6, 0x8b, 0xf8, 0xa8, 0x59, 0xeb, 0xe9, 0x21,
	0xf4, 0xb0, 0x67, 0xa7, 0x51, 0xa9, 0xdf, 0x76, 0xf9, 0x2f, 0xea, 0x87, 0xbf, 0xd3, 0x69, 0xe0,
	0x4b, 0xf8, 0x7f, 0x6f, 0xd7, 0xaf, 0x89, 0x08, 0x68, 0xf2, 0x87, 0x07, 0x8e, 0xa2, 0x4e, 0x03,
	0x07, 0x70, 0x72, 0x27, 0x3e, 0xf8, 0xa0, 0xa7, 0xc3, 0x19, 0xb3, 0xec, 0x63, 0xf2, 0x15, 0xd1,
	0x69, 0xcc, 0xe0, 0x6a, 0x9b, 0xd6, 0x8b, 0xc6, 0x05, 0x9a, 0xb7, 0xe5, 0x5f, 0xf8, 0xe2, 0x77,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x3c, 0xf5, 0x25, 0xcd, 0x97, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QuestionServiveClient is the client API for QuestionServive service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QuestionServiveClient interface {
	// 创建
	CreateQuestion(ctx context.Context, in *Question, opts ...grpc.CallOption) (*CreateQuestionResponse, error)
	// 更新
	UpdateQuestion(ctx context.Context, in *Question, opts ...grpc.CallOption) (*UpdateQuestionResponse, error)
	// 查看详情
	GetQuestionDetail(ctx context.Context, in *Question, opts ...grpc.CallOption) (*Question, error)
	// 查看列表
	GetQuestionList(ctx context.Context, in *GetQuestionListRequest, opts ...grpc.CallOption) (*QuestionList, error)
}

type questionServiveClient struct {
	cc *grpc.ClientConn
}

func NewQuestionServiveClient(cc *grpc.ClientConn) QuestionServiveClient {
	return &questionServiveClient{cc}
}

func (c *questionServiveClient) CreateQuestion(ctx context.Context, in *Question, opts ...grpc.CallOption) (*CreateQuestionResponse, error) {
	out := new(CreateQuestionResponse)
	err := c.cc.Invoke(ctx, "/interview.question.QuestionServive/CreateQuestion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionServiveClient) UpdateQuestion(ctx context.Context, in *Question, opts ...grpc.CallOption) (*UpdateQuestionResponse, error) {
	out := new(UpdateQuestionResponse)
	err := c.cc.Invoke(ctx, "/interview.question.QuestionServive/UpdateQuestion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionServiveClient) GetQuestionDetail(ctx context.Context, in *Question, opts ...grpc.CallOption) (*Question, error) {
	out := new(Question)
	err := c.cc.Invoke(ctx, "/interview.question.QuestionServive/GetQuestionDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionServiveClient) GetQuestionList(ctx context.Context, in *GetQuestionListRequest, opts ...grpc.CallOption) (*QuestionList, error) {
	out := new(QuestionList)
	err := c.cc.Invoke(ctx, "/interview.question.QuestionServive/GetQuestionList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuestionServiveServer is the server API for QuestionServive service.
type QuestionServiveServer interface {
	// 创建
	CreateQuestion(context.Context, *Question) (*CreateQuestionResponse, error)
	// 更新
	UpdateQuestion(context.Context, *Question) (*UpdateQuestionResponse, error)
	// 查看详情
	GetQuestionDetail(context.Context, *Question) (*Question, error)
	// 查看列表
	GetQuestionList(context.Context, *GetQuestionListRequest) (*QuestionList, error)
}

func RegisterQuestionServiveServer(s *grpc.Server, srv QuestionServiveServer) {
	s.RegisterService(&_QuestionServive_serviceDesc, srv)
}

func _QuestionServive_CreateQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Question)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServiveServer).CreateQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interview.question.QuestionServive/CreateQuestion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServiveServer).CreateQuestion(ctx, req.(*Question))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestionServive_UpdateQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Question)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServiveServer).UpdateQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interview.question.QuestionServive/UpdateQuestion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServiveServer).UpdateQuestion(ctx, req.(*Question))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestionServive_GetQuestionDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Question)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServiveServer).GetQuestionDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interview.question.QuestionServive/GetQuestionDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServiveServer).GetQuestionDetail(ctx, req.(*Question))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestionServive_GetQuestionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuestionListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServiveServer).GetQuestionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interview.question.QuestionServive/GetQuestionList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServiveServer).GetQuestionList(ctx, req.(*GetQuestionListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _QuestionServive_serviceDesc = grpc.ServiceDesc{
	ServiceName: "interview.question.QuestionServive",
	HandlerType: (*QuestionServiveServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateQuestion",
			Handler:    _QuestionServive_CreateQuestion_Handler,
		},
		{
			MethodName: "UpdateQuestion",
			Handler:    _QuestionServive_UpdateQuestion_Handler,
		},
		{
			MethodName: "GetQuestionDetail",
			Handler:    _QuestionServive_GetQuestionDetail_Handler,
		},
		{
			MethodName: "GetQuestionList",
			Handler:    _QuestionServive_GetQuestionList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "question.proto",
}
